export const CURATED_CLIP_DEMO = {
  id: "UjnoRZLR10",
  videoUrl:
    "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.raod.AP.mp4",
  videoUrlForDownload:
    "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.rao.rM.mp4",
  outputs: [
    {
      type: "VIDEO",
      name: "re_layout.add_audio.overlay.down_scale",
      hasOverlay: true,
      hasReLayout: true,
      size: "small",
      file: {
        driver: "GCS",
        path: "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.raod.AP.mp4",
        hasAudio: true,
        hasVideo: true,
        profile: {
          durationMs: 38205,
          height: 480,
          width: 270,
          fps: "24000/1001",
        },
      },
    },
    {
      type: "VIDEO",
      name: "re_layout.add_audio.overlay",
      hasOverlay: true,
      hasReLayout: true,
      size: "full",
      file: {
        driver: "GCS",
        path: "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.rao.rM.mp4",
        hasAudio: true,
        hasVideo: true,
        profile: {
          durationMs: 38205,
          height: 1080,
          width: 608,
          fps: "24000/1001",
        },
      },
    },
    {
      type: "VIDEO",
      name: "re_layout.add_audio",
      hasOverlay: false,
      hasReLayout: true,
      size: "full",
      file: {
        driver: "GCS",
        path: "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.ra.Ja.mp4",
        hasAudio: true,
        hasVideo: true,
        profile: {
          durationMs: 38205,
          height: 1080,
          width: 608,
          fps: "24000/1001",
        },
      },
    },
    {
      type: "VIDEO",
      name: "re_layout.add_audio.down_scale",
      hasOverlay: false,
      hasReLayout: true,
      size: "small",
      file: {
        driver: "GCS",
        path: "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.rad.mg.mp4",
        hasAudio: true,
        hasVideo: true,
        profile: {
          durationMs: 38205,
          height: 480,
          width: 270,
          fps: "24000/1001",
        },
      },
    },
    {
      type: "VIDEO",
      name: "add_audio",
      hasReLayout: false,
      hasOverlay: false,
      size: "full",
      file: {
        driver: "GCS",
        path: "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.a.3M.mp4",
        hasAudio: true,
        hasVideo: true,
        profile: {
          durationMs: 38123,
          height: 1080,
          width: 1920,
          fps: "24000/1001",
        },
      },
    },
    {
      type: "VIDEO",
      name: "add_audio.down_scale",
      hasReLayout: false,
      hasOverlay: false,
      size: "small",
      file: {
        driver: "GCS",
        path: "https://storage.googleapis.com/opus-clip-pub/projects_preview/demo-el/20230511032800826.RC/clip.UjnoRZLR10.ad.YR.mp4",
        hasAudio: true,
        hasVideo: true,
        profile: {
          durationMs: 38123,
          height: 480,
          width: 854,
          fps: "24000/1001",
        },
      },
    },
  ],
  durationMs: 38205,
  title: "Insane Reality: How Powerful AI Can Be Hijacked and Controlled",
  text: " You know, like some evil dictator or country could send their intelligence agency to go steal it and gain control. It just becomes a very unstable situation. I think if you've got any incredibly powerful AI, you just don't know who's going to control that. So it's not as I think that the risk is that the AI would develop a will of its own right off the bat. I think it's more the concern is that someone may use it in a way that is bad. Even if they weren't going to use it in a way that's bad, that somebody could take it from them and use it in a way that's bad. That I think is quite a big danger.",
  score: 92,
  reason:
    "The video provides valuable insights on the potential risks and dangers of AI, but could benefit from more engaging content and relatable examples. The hook sentence lacks context, but the content is complete and informative. Overall, it encourages critical thinking about AI's impact on society.",
  curation: {
    id: "UjnoRZLR10",
    title: "Insane Reality: How Powerful AI Can Be Hijacked and Controlled",
    text: " You know, like some evil dictator or country could send their intelligence agency to go steal it and gain control. It just becomes a very unstable situation. I think if you've got any incredibly powerful AI, you just don't know who's going to control that. So it's not as I think that the risk is that the AI would develop a will of its own right off the bat. I think it's more the concern is that someone may use it in a way that is bad. Even if they weren't going to use it in a way that's bad, that somebody could take it from them and use it in a way that's bad. That I think is quite a big danger.",
    scenes: [
      {
        id: "S.000",
        source: {
          offsetStartMs: 730000,
          offsetEndMs: 768120,
        },
        transcriptSegments: [
          {
            text: " You know, like some evil dictator or country could send their intelligence agency to go steal it and gain control. It just becomes a very unstable situation. I think if you've got any incredibly powerful AI, you just don't know who's going to control that. So it's not as I think that the risk is that the AI would develop a will of its own right off the bat. I think it's more the concern is that someone may use it in a way that is bad. Even if they weren't going to use it in a way that's bad, that somebody could take it from them and use it in a way that's bad. That I think is quite a big danger.",
            words: [
              {
                word: " You",
                offsetStartMs: 730000,
                offsetEndMs: 730000,
                durationMs: 0,
                idx: 1977,
              },
              {
                word: " know,",
                offsetStartMs: 730000,
                offsetEndMs: 730220,
                durationMs: 220,
                idx: 1978,
              },
              {
                word: " like",
                offsetStartMs: 730420,
                offsetEndMs: 730540,
                durationMs: 120,
                idx: 1979,
              },
              {
                word: " some",
                offsetStartMs: 730540,
                offsetEndMs: 730680,
                durationMs: 140,
                idx: 1980,
              },
              {
                word: " evil",
                offsetStartMs: 730680,
                offsetEndMs: 730920,
                durationMs: 240,
                idx: 1981,
              },
              {
                word: " dictator",
                offsetStartMs: 730920,
                offsetEndMs: 731300,
                durationMs: 380,
                idx: 1982,
              },
              {
                word: " or",
                offsetStartMs: 731300,
                offsetEndMs: 731900,
                durationMs: 600,
                idx: 1983,
              },
              {
                word: " country",
                offsetStartMs: 731900,
                offsetEndMs: 732220,
                durationMs: 320,
                idx: 1984,
              },
              {
                word: " could",
                offsetStartMs: 732220,
                offsetEndMs: 732420,
                durationMs: 200,
                idx: 1985,
              },
              {
                word: " send",
                offsetStartMs: 732420,
                offsetEndMs: 732660,
                durationMs: 240,
                idx: 1986,
              },
              {
                word: " their",
                offsetStartMs: 732660,
                offsetEndMs: 733020,
                durationMs: 360,
                idx: 1987,
              },
              {
                word: " intelligence",
                offsetStartMs: 733020,
                offsetEndMs: 734020,
                durationMs: 1000,
                idx: 1988,
              },
              {
                word: " agency",
                offsetStartMs: 734020,
                offsetEndMs: 734420,
                durationMs: 400,
                idx: 1989,
              },
              {
                word: " to",
                offsetStartMs: 734420,
                offsetEndMs: 734720,
                durationMs: 300,
                idx: 1990,
              },
              {
                word: " go",
                offsetStartMs: 734720,
                offsetEndMs: 734820,
                durationMs: 100,
                idx: 1991,
              },
              {
                word: " steal",
                offsetStartMs: 734820,
                offsetEndMs: 735040,
                durationMs: 220,
                idx: 1992,
              },
              {
                word: " it",
                offsetStartMs: 735040,
                offsetEndMs: 735260,
                durationMs: 220,
                idx: 1993,
              },
              {
                word: " and",
                offsetStartMs: 735260,
                offsetEndMs: 735440,
                durationMs: 180,
                idx: 1994,
              },
              {
                word: " gain",
                offsetStartMs: 735440,
                offsetEndMs: 735620,
                durationMs: 180,
                idx: 1995,
              },
              {
                word: " control.",
                offsetStartMs: 735620,
                offsetEndMs: 736100,
                durationMs: 480,
                idx: 1996,
              },
              {
                word: " It",
                offsetStartMs: 736620,
                offsetEndMs: 736740,
                durationMs: 120,
                idx: 1997,
              },
              {
                word: " just",
                offsetStartMs: 736740,
                offsetEndMs: 736840,
                durationMs: 100,
                idx: 1998,
              },
              {
                word: " becomes",
                offsetStartMs: 736840,
                offsetEndMs: 737100,
                durationMs: 260,
                idx: 1999,
              },
              {
                word: " a",
                offsetStartMs: 737100,
                offsetEndMs: 737260,
                durationMs: 160,
                idx: 2000,
              },
              {
                word: " very",
                offsetStartMs: 737260,
                offsetEndMs: 737420,
                durationMs: 160,
                idx: 2001,
              },
              {
                word: " unstable",
                offsetStartMs: 737420,
                offsetEndMs: 737860,
                durationMs: 440,
                idx: 2002,
              },
              {
                word: " situation.",
                offsetStartMs: 737860,
                offsetEndMs: 738340,
                durationMs: 480,
                idx: 2003,
              },
              {
                word: " I",
                offsetStartMs: 738600,
                offsetEndMs: 738600,
                durationMs: 0,
                idx: 2004,
              },
              {
                word: " think",
                offsetStartMs: 738600,
                offsetEndMs: 738760,
                durationMs: 160,
                idx: 2005,
              },
              {
                word: " if",
                offsetStartMs: 738760,
                offsetEndMs: 738900,
                durationMs: 140,
                idx: 2006,
              },
              {
                word: " you've",
                offsetStartMs: 738900,
                offsetEndMs: 739100,
                durationMs: 200,
                idx: 2007,
              },
              {
                word: " got",
                offsetStartMs: 739100,
                offsetEndMs: 739240,
                durationMs: 140,
                idx: 2008,
              },
              {
                word: " any",
                offsetStartMs: 739240,
                offsetEndMs: 739680,
                durationMs: 440,
                idx: 2009,
              },
              {
                word: " incredibly",
                offsetStartMs: 739680,
                offsetEndMs: 742060,
                durationMs: 2380,
                idx: 2010,
              },
              {
                word: " powerful",
                offsetStartMs: 742060,
                offsetEndMs: 742660,
                durationMs: 600,
                idx: 2011,
              },
              {
                word: " AI,",
                offsetStartMs: 742660,
                offsetEndMs: 743060,
                durationMs: 400,
                idx: 2012,
              },
              {
                word: " you",
                offsetStartMs: 744520,
                offsetEndMs: 745440,
                durationMs: 920,
                idx: 2013,
              },
              {
                word: " just",
                offsetStartMs: 745440,
                offsetEndMs: 745600,
                durationMs: 160,
                idx: 2014,
              },
              {
                word: " don't",
                offsetStartMs: 745600,
                offsetEndMs: 745740,
                durationMs: 140,
                idx: 2015,
              },
              {
                word: " know",
                offsetStartMs: 745740,
                offsetEndMs: 745940,
                durationMs: 200,
                idx: 2016,
              },
              {
                word: " who's",
                offsetStartMs: 745940,
                offsetEndMs: 746380,
                durationMs: 440,
                idx: 2017,
              },
              {
                word: " going",
                offsetStartMs: 746380,
                offsetEndMs: 746740,
                durationMs: 360,
                idx: 2018,
              },
              {
                word: " to",
                offsetStartMs: 746740,
                offsetEndMs: 746820,
                durationMs: 80,
                idx: 2019,
              },
              {
                word: " control",
                offsetStartMs: 746820,
                offsetEndMs: 747100,
                durationMs: 280,
                idx: 2020,
              },
              {
                word: " that.",
                offsetStartMs: 747100,
                offsetEndMs: 747300,
                durationMs: 200,
                idx: 2021,
              },
              {
                word: " So",
                offsetStartMs: 747520,
                offsetEndMs: 747520,
                durationMs: 0,
                idx: 2022,
              },
              {
                word: " it's",
                offsetStartMs: 747520,
                offsetEndMs: 748320,
                durationMs: 800,
                idx: 2023,
              },
              {
                word: " not",
                offsetStartMs: 748320,
                offsetEndMs: 748420,
                durationMs: 100,
                idx: 2024,
              },
              {
                word: " as",
                offsetStartMs: 748420,
                offsetEndMs: 748520,
                durationMs: 100,
                idx: 2025,
              },
              {
                word: " I",
                offsetStartMs: 748520,
                offsetEndMs: 748660,
                durationMs: 140,
                idx: 2026,
              },
              {
                word: " think",
                offsetStartMs: 748660,
                offsetEndMs: 748820,
                durationMs: 160,
                idx: 2027,
              },
              {
                word: " that",
                offsetStartMs: 748820,
                offsetEndMs: 748980,
                durationMs: 160,
                idx: 2028,
              },
              {
                word: " the",
                offsetStartMs: 748980,
                offsetEndMs: 749100,
                durationMs: 120,
                idx: 2029,
              },
              {
                word: " risk",
                offsetStartMs: 749100,
                offsetEndMs: 749260,
                durationMs: 160,
                idx: 2030,
              },
              {
                word: " is",
                offsetStartMs: 749260,
                offsetEndMs: 749480,
                durationMs: 220,
                idx: 2031,
              },
              {
                word: " that",
                offsetStartMs: 749480,
                offsetEndMs: 749640,
                durationMs: 160,
                idx: 2032,
              },
              {
                word: " the",
                offsetStartMs: 749640,
                offsetEndMs: 749740,
                durationMs: 100,
                idx: 2033,
              },
              {
                word: " AI",
                offsetStartMs: 749740,
                offsetEndMs: 749980,
                durationMs: 240,
                idx: 2034,
              },
              {
                word: " would",
                offsetStartMs: 749980,
                offsetEndMs: 750200,
                durationMs: 220,
                idx: 2035,
              },
              {
                word: " develop",
                offsetStartMs: 750200,
                offsetEndMs: 750480,
                durationMs: 280,
                idx: 2036,
              },
              {
                word: " a",
                offsetStartMs: 750480,
                offsetEndMs: 750640,
                durationMs: 160,
                idx: 2037,
              },
              {
                word: " will",
                offsetStartMs: 750640,
                offsetEndMs: 750720,
                durationMs: 80,
                idx: 2038,
              },
              {
                word: " of",
                offsetStartMs: 750720,
                offsetEndMs: 750820,
                durationMs: 100,
                idx: 2039,
              },
              {
                word: " its",
                offsetStartMs: 750820,
                offsetEndMs: 750960,
                durationMs: 140,
                idx: 2040,
              },
              {
                word: " own",
                offsetStartMs: 750960,
                offsetEndMs: 751160,
                durationMs: 200,
                idx: 2041,
              },
              {
                word: " right",
                offsetStartMs: 751160,
                offsetEndMs: 751380,
                durationMs: 220,
                idx: 2042,
              },
              {
                word: " off",
                offsetStartMs: 751380,
                offsetEndMs: 751500,
                durationMs: 120,
                idx: 2043,
              },
              {
                word: " the",
                offsetStartMs: 751500,
                offsetEndMs: 751700,
                durationMs: 200,
                idx: 2044,
              },
              {
                word: " bat.",
                offsetStartMs: 751700,
                offsetEndMs: 751800,
                durationMs: 100,
                idx: 2045,
              },
              {
                word: " I",
                offsetStartMs: 752000,
                offsetEndMs: 752000,
                durationMs: 0,
                idx: 2046,
              },
              {
                word: " think",
                offsetStartMs: 752000,
                offsetEndMs: 752180,
                durationMs: 180,
                idx: 2047,
              },
              {
                word: " it's",
                offsetStartMs: 752180,
                offsetEndMs: 752720,
                durationMs: 540,
                idx: 2048,
              },
              {
                word: " more",
                offsetStartMs: 752720,
                offsetEndMs: 752920,
                durationMs: 200,
                idx: 2049,
              },
              {
                word: " the",
                offsetStartMs: 752920,
                offsetEndMs: 753900,
                durationMs: 980,
                idx: 2050,
              },
              {
                word: " concern",
                offsetStartMs: 753900,
                offsetEndMs: 754180,
                durationMs: 280,
                idx: 2051,
              },
              {
                word: " is",
                offsetStartMs: 754180,
                offsetEndMs: 754360,
                durationMs: 180,
                idx: 2052,
              },
              {
                word: " that",
                offsetStartMs: 754360,
                offsetEndMs: 754680,
                durationMs: 320,
                idx: 2053,
              },
              {
                word: " someone",
                offsetStartMs: 754680,
                offsetEndMs: 755780,
                durationMs: 1100,
                idx: 2054,
              },
              {
                word: " may",
                offsetStartMs: 755780,
                offsetEndMs: 757600,
                durationMs: 1820,
                idx: 2055,
              },
              {
                word: " use",
                offsetStartMs: 757600,
                offsetEndMs: 757900,
                durationMs: 300,
                idx: 2056,
              },
              {
                word: " it",
                offsetStartMs: 757900,
                offsetEndMs: 758060,
                durationMs: 160,
                idx: 2057,
              },
              {
                word: " in",
                offsetStartMs: 758060,
                offsetEndMs: 758180,
                durationMs: 120,
                idx: 2058,
              },
              {
                word: " a",
                offsetStartMs: 758180,
                offsetEndMs: 758280,
                durationMs: 100,
                idx: 2059,
              },
              {
                word: " way",
                offsetStartMs: 758280,
                offsetEndMs: 758380,
                durationMs: 100,
                idx: 2060,
              },
              {
                word: " that",
                offsetStartMs: 758380,
                offsetEndMs: 758560,
                durationMs: 180,
                idx: 2061,
              },
              {
                word: " is",
                offsetStartMs: 758560,
                offsetEndMs: 758760,
                durationMs: 200,
                idx: 2062,
              },
              {
                word: " bad.",
                offsetStartMs: 758760,
                offsetEndMs: 759100,
                durationMs: 340,
                idx: 2063,
              },
              {
                word: " Even",
                offsetStartMs: 760260,
                offsetEndMs: 760860,
                durationMs: 600,
                idx: 2064,
              },
              {
                word: " if",
                offsetStartMs: 760860,
                offsetEndMs: 761080,
                durationMs: 220,
                idx: 2065,
              },
              {
                word: " they",
                offsetStartMs: 761080,
                offsetEndMs: 761280,
                durationMs: 200,
                idx: 2066,
              },
              {
                word: " weren't",
                offsetStartMs: 761280,
                offsetEndMs: 761480,
                durationMs: 200,
                idx: 2067,
              },
              {
                word: " going",
                offsetStartMs: 761480,
                offsetEndMs: 761640,
                durationMs: 160,
                idx: 2068,
              },
              {
                word: " to",
                offsetStartMs: 761640,
                offsetEndMs: 761720,
                durationMs: 80,
                idx: 2069,
              },
              {
                word: " use",
                offsetStartMs: 761720,
                offsetEndMs: 761840,
                durationMs: 120,
                idx: 2070,
              },
              {
                word: " it",
                offsetStartMs: 761840,
                offsetEndMs: 761960,
                durationMs: 120,
                idx: 2071,
              },
              {
                word: " in",
                offsetStartMs: 761960,
                offsetEndMs: 762000,
                durationMs: 40,
                idx: 2072,
              },
              {
                word: " a",
                offsetStartMs: 762000,
                offsetEndMs: 762080,
                durationMs: 80,
                idx: 2073,
              },
              {
                word: " way",
                offsetStartMs: 762080,
                offsetEndMs: 762180,
                durationMs: 100,
                idx: 2074,
              },
              {
                word: " that's",
                offsetStartMs: 762180,
                offsetEndMs: 762360,
                durationMs: 180,
                idx: 2075,
              },
              {
                word: " bad,",
                offsetStartMs: 762360,
                offsetEndMs: 762520,
                durationMs: 160,
                idx: 2076,
              },
              {
                word: " that",
                offsetStartMs: 762520,
                offsetEndMs: 762640,
                durationMs: 120,
                idx: 2077,
              },
              {
                word: " somebody",
                offsetStartMs: 762640,
                offsetEndMs: 762920,
                durationMs: 280,
                idx: 2078,
              },
              {
                word: " could",
                offsetStartMs: 762920,
                offsetEndMs: 763200,
                durationMs: 280,
                idx: 2079,
              },
              {
                word: " take",
                offsetStartMs: 763200,
                offsetEndMs: 763440,
                durationMs: 240,
                idx: 2080,
              },
              {
                word: " it",
                offsetStartMs: 763440,
                offsetEndMs: 763620,
                durationMs: 180,
                idx: 2081,
              },
              {
                word: " from",
                offsetStartMs: 763620,
                offsetEndMs: 763820,
                durationMs: 200,
                idx: 2082,
              },
              {
                word: " them",
                offsetStartMs: 763820,
                offsetEndMs: 764040,
                durationMs: 220,
                idx: 2083,
              },
              {
                word: " and",
                offsetStartMs: 764040,
                offsetEndMs: 764200,
                durationMs: 160,
                idx: 2084,
              },
              {
                word: " use",
                offsetStartMs: 764200,
                offsetEndMs: 764340,
                durationMs: 140,
                idx: 2085,
              },
              {
                word: " it",
                offsetStartMs: 764340,
                offsetEndMs: 764480,
                durationMs: 140,
                idx: 2086,
              },
              {
                word: " in",
                offsetStartMs: 764480,
                offsetEndMs: 764580,
                durationMs: 100,
                idx: 2087,
              },
              {
                word: " a",
                offsetStartMs: 764580,
                offsetEndMs: 764640,
                durationMs: 60,
                idx: 2088,
              },
              {
                word: " way",
                offsetStartMs: 764640,
                offsetEndMs: 764760,
                durationMs: 120,
                idx: 2089,
              },
              {
                word: " that's",
                offsetStartMs: 764760,
                offsetEndMs: 764980,
                durationMs: 220,
                idx: 2090,
              },
              {
                word: " bad.",
                offsetStartMs: 764980,
                offsetEndMs: 765240,
                durationMs: 260,
                idx: 2091,
              },
              {
                word: " That",
                offsetStartMs: 766120,
                offsetEndMs: 766420,
                durationMs: 300,
                idx: 2092,
              },
              {
                word: " I",
                offsetStartMs: 766420,
                offsetEndMs: 766660,
                durationMs: 240,
                idx: 2093,
              },
              {
                word: " think",
                offsetStartMs: 766660,
                offsetEndMs: 766800,
                durationMs: 140,
                idx: 2094,
              },
              {
                word: " is",
                offsetStartMs: 766800,
                offsetEndMs: 766920,
                durationMs: 120,
                idx: 2095,
              },
              {
                word: " quite",
                offsetStartMs: 766920,
                offsetEndMs: 767360,
                durationMs: 440,
                idx: 2096,
              },
              {
                word: " a",
                offsetStartMs: 767360,
                offsetEndMs: 767460,
                durationMs: 100,
                idx: 2097,
              },
              {
                word: " big",
                offsetStartMs: 767460,
                offsetEndMs: 767560,
                durationMs: 100,
                idx: 2098,
              },
              {
                word: " danger.",
                offsetStartMs: 767560,
                offsetEndMs: 767840,
                durationMs: 280,
                idx: 2099,
              },
            ],
            offsetStartMs: 730000,
            offsetEndMs: 768120,
          },
        ],
      },
    ],
    rawScore: 6.5,
    archId: "HP",
    reason:
      "The video provides valuable insights on the potential risks and dangers of AI, but could benefit from more engaging content and relatable examples. The hook sentence lacks context, but the content is complete and informative. Overall, it encourages critical thinking about AI's impact on society.",
    score: 92,
    vhook: "Elon Musks warning on the dangers of powerful AI",
  },
  overlayPlans: {
    captionPlans: [
      {
        sceneId: "S.000",
        frames: [
          {
            elements: [
              {
                content: "You",
                color: 0,
                offsetStartMs: 730000,
                offsetEndMs: 730000,
                wrap: false,
              },
              {
                content: "know",
                color: 0,
                offsetStartMs: 730000,
                offsetEndMs: 730220,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 730000,
              offsetEndMs: 730220,
            },
          },
          {
            elements: [
              {
                content: "like",
                color: 0,
                offsetStartMs: 730420,
                offsetEndMs: 730540,
                wrap: false,
              },
              {
                content: "some",
                color: 0,
                offsetStartMs: 730540,
                offsetEndMs: 730680,
                wrap: false,
              },
              {
                content: "evil",
                color: 2,
                offsetStartMs: 730680,
                offsetEndMs: 730920,
                wrap: true,
              },
              {
                content: "dictator",
                color: 2,
                offsetStartMs: 730920,
                offsetEndMs: 731300,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 730420,
              offsetEndMs: 731300,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
              coveredLayers: [
                {
                  name: "VHOOK",
                  coveredLayerSource: {
                    offsetStartMs: 730000,
                    offsetEndMs: 733000,
                  },
                },
              ],
            },
          },
          {
            elements: [
              {
                content: "or",
                color: 0,
                offsetStartMs: 731300,
                offsetEndMs: 731900,
                wrap: false,
              },
              {
                content: "country",
                color: 0,
                offsetStartMs: 731900,
                offsetEndMs: 732220,
                wrap: true,
              },
              {
                content: "could",
                color: 0,
                offsetStartMs: 732220,
                offsetEndMs: 732420,
                wrap: false,
              },
              {
                content: "send",
                color: 0,
                offsetStartMs: 732420,
                offsetEndMs: 732660,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 731300,
              offsetEndMs: 732660,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
              coveredLayers: [
                {
                  name: "VHOOK",
                  coveredLayerSource: {
                    offsetStartMs: 730000,
                    offsetEndMs: 733000,
                  },
                },
              ],
            },
          },
          {
            elements: [
              {
                content: "their",
                color: 0,
                offsetStartMs: 732660,
                offsetEndMs: 733020,
                wrap: true,
              },
              {
                content: "intelligence",
                color: 2,
                offsetStartMs: 733020,
                offsetEndMs: 734020,
                wrap: true,
              },
              {
                content: "agency",
                color: 2,
                offsetStartMs: 734020,
                offsetEndMs: 734420,
                wrap: false,
              },
              {
                content: "to",
                color: 0,
                offsetStartMs: 734420,
                offsetEndMs: 734720,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 732660,
              offsetEndMs: 734720,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
              coveredLayers: [
                {
                  name: "VHOOK",
                  coveredLayerSource: {
                    offsetStartMs: 730000,
                    offsetEndMs: 733000,
                  },
                },
              ],
            },
          },
          {
            elements: [
              {
                content: "go",
                color: 0,
                offsetStartMs: 734720,
                offsetEndMs: 734820,
                wrap: false,
              },
              {
                content: "steal",
                color: 0,
                offsetStartMs: 734820,
                offsetEndMs: 735040,
                wrap: false,
              },
              {
                content: "it",
                color: 0,
                offsetStartMs: 735040,
                offsetEndMs: 735260,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 734720,
              offsetEndMs: 735260,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "and",
                color: 0,
                offsetStartMs: 735260,
                offsetEndMs: 735440,
                wrap: false,
              },
              {
                content: "gain",
                color: 1,
                offsetStartMs: 735440,
                offsetEndMs: 735620,
                wrap: true,
              },
              {
                content: "control",
                color: 1,
                offsetStartMs: 735620,
                offsetEndMs: 736100,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 735260,
              offsetEndMs: 736100,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "It",
                color: 0,
                offsetStartMs: 736620,
                offsetEndMs: 736740,
                wrap: false,
              },
              {
                content: "just",
                color: 0,
                offsetStartMs: 736740,
                offsetEndMs: 736840,
                wrap: false,
              },
              {
                content: "becomes",
                color: 0,
                offsetStartMs: 736840,
                offsetEndMs: 737100,
                wrap: true,
              },
            ],
            source: {
              offsetStartMs: 736620,
              offsetEndMs: 737100,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "a",
                color: 0,
                offsetStartMs: 737100,
                offsetEndMs: 737260,
                wrap: false,
              },
              {
                content: "very",
                color: 0,
                offsetStartMs: 737260,
                offsetEndMs: 737420,
                wrap: false,
              },
              {
                content: "unstable",
                color: 2,
                offsetStartMs: 737420,
                offsetEndMs: 737860,
                wrap: true,
              },
              {
                content: "situation",
                color: 2,
                offsetStartMs: 737860,
                offsetEndMs: 738340,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 737100,
              offsetEndMs: 738340,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "I",
                color: 0,
                offsetStartMs: 738600,
                offsetEndMs: 738600,
                wrap: false,
              },
              {
                content: "think",
                color: 0,
                offsetStartMs: 738600,
                offsetEndMs: 738760,
                wrap: false,
              },
              {
                content: "if",
                color: 0,
                offsetStartMs: 738760,
                offsetEndMs: 738900,
                wrap: false,
              },
              {
                content: "you've",
                color: 0,
                offsetStartMs: 738900,
                offsetEndMs: 739100,
                wrap: true,
              },
              {
                content: "got",
                color: 0,
                offsetStartMs: 739100,
                offsetEndMs: 739240,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 738600,
              offsetEndMs: 739240,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "any",
                color: 0,
                offsetStartMs: 739240,
                offsetEndMs: 739680,
                wrap: false,
              },
              {
                content: "incredibly",
                color: 0,
                offsetStartMs: 739680,
                offsetEndMs: 742060,
                wrap: true,
              },
              {
                content: "powerful",
                color: 0,
                offsetStartMs: 742060,
                offsetEndMs: 742660,
                wrap: false,
              },
              {
                content: "AI",
                color: 2,
                offsetStartMs: 742660,
                offsetEndMs: 743060,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 739240,
              offsetEndMs: 743060,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "you",
                color: 0,
                offsetStartMs: 744520,
                offsetEndMs: 745440,
                wrap: false,
              },
              {
                content: "just",
                color: 0,
                offsetStartMs: 745440,
                offsetEndMs: 745600,
                wrap: false,
              },
              {
                content: "don't",
                color: 0,
                offsetStartMs: 745600,
                offsetEndMs: 745740,
                wrap: true,
              },
              {
                content: "know",
                color: 0,
                offsetStartMs: 745740,
                offsetEndMs: 745940,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 744520,
              offsetEndMs: 745940,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "who's",
                color: 0,
                offsetStartMs: 745940,
                offsetEndMs: 746380,
                wrap: false,
              },
              {
                content: "going",
                color: 0,
                offsetStartMs: 746380,
                offsetEndMs: 746740,
                wrap: false,
              },
              {
                content: "to",
                color: 0,
                offsetStartMs: 746740,
                offsetEndMs: 746820,
                wrap: true,
              },
              {
                content: "control",
                color: 1,
                offsetStartMs: 746820,
                offsetEndMs: 747100,
                wrap: false,
              },
              {
                content: "that",
                color: 1,
                offsetStartMs: 747100,
                offsetEndMs: 747300,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 745940,
              offsetEndMs: 747300,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "So",
                color: 0,
                offsetStartMs: 747520,
                offsetEndMs: 747520,
                revisedContent: "So",
                wrap: false,
              },
              {
                content: "it's",
                color: 0,
                offsetStartMs: 747520,
                offsetEndMs: 748320,
                wrap: false,
              },
              {
                content: "not",
                color: 0,
                offsetStartMs: 748320,
                offsetEndMs: 748420,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 747520,
              offsetEndMs: 748420,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "as",
                color: 0,
                offsetStartMs: 748420,
                offsetEndMs: 748520,
                wrap: false,
              },
              {
                content: "I",
                color: 0,
                offsetStartMs: 748520,
                offsetEndMs: 748660,
                wrap: false,
              },
              {
                content: "think",
                color: 0,
                offsetStartMs: 748660,
                offsetEndMs: 748820,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 748420,
              offsetEndMs: 748820,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "that",
                color: 0,
                offsetStartMs: 748820,
                offsetEndMs: 748980,
                wrap: false,
              },
              {
                content: "the",
                color: 0,
                offsetStartMs: 748980,
                offsetEndMs: 749100,
                wrap: false,
              },
              {
                content: "risk",
                color: 0,
                offsetStartMs: 749100,
                offsetEndMs: 749260,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 748820,
              offsetEndMs: 749260,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "is",
                color: 0,
                offsetStartMs: 749260,
                offsetEndMs: 749480,
                wrap: false,
              },
              {
                content: "that",
                color: 0,
                offsetStartMs: 749480,
                offsetEndMs: 749640,
                wrap: false,
              },
              {
                content: "the",
                color: 0,
                offsetStartMs: 749640,
                offsetEndMs: 749740,
                wrap: false,
              },
              {
                content: "AI",
                color: 2,
                offsetStartMs: 749740,
                offsetEndMs: 749980,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 749260,
              offsetEndMs: 749980,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "would",
                color: 0,
                offsetStartMs: 749980,
                offsetEndMs: 750200,
                wrap: false,
              },
              {
                content: "develop",
                color: 0,
                offsetStartMs: 750200,
                offsetEndMs: 750480,
                wrap: true,
              },
              {
                content: "a",
                color: 0,
                offsetStartMs: 750480,
                offsetEndMs: 750640,
                wrap: false,
              },
              {
                content: "will",
                color: 0,
                offsetStartMs: 750640,
                offsetEndMs: 750720,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 749980,
              offsetEndMs: 750720,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "of",
                color: 0,
                offsetStartMs: 750720,
                offsetEndMs: 750820,
                wrap: false,
              },
              {
                content: "its",
                color: 0,
                offsetStartMs: 750820,
                offsetEndMs: 750960,
                wrap: false,
              },
              {
                content: "own",
                color: 2,
                offsetStartMs: 750960,
                offsetEndMs: 751160,
                wrap: false,
              },
              {
                content: "right",
                color: 2,
                offsetStartMs: 751160,
                offsetEndMs: 751380,
                wrap: true,
              },
            ],
            source: {
              offsetStartMs: 750720,
              offsetEndMs: 751380,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "off",
                color: 0,
                offsetStartMs: 751380,
                offsetEndMs: 751500,
                wrap: false,
              },
              {
                content: "the",
                color: 0,
                offsetStartMs: 751500,
                offsetEndMs: 751700,
                wrap: false,
              },
              {
                content: "bat",
                color: 0,
                offsetStartMs: 751700,
                offsetEndMs: 751800,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 751380,
              offsetEndMs: 751800,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "I",
                color: 0,
                offsetStartMs: 752000,
                offsetEndMs: 752000,
                wrap: false,
              },
              {
                content: "think",
                color: 0,
                offsetStartMs: 752000,
                offsetEndMs: 752180,
                wrap: false,
              },
              {
                content: "it's",
                color: 0,
                offsetStartMs: 752180,
                offsetEndMs: 752720,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 752000,
              offsetEndMs: 752720,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "more",
                color: 0,
                offsetStartMs: 752720,
                offsetEndMs: 752920,
                wrap: false,
              },
              {
                content: "the",
                color: 0,
                offsetStartMs: 752920,
                offsetEndMs: 753900,
                wrap: true,
              },
              {
                content: "concern",
                color: 0,
                offsetStartMs: 753900,
                offsetEndMs: 754180,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 752720,
              offsetEndMs: 754180,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "is",
                color: 0,
                offsetStartMs: 754180,
                offsetEndMs: 754360,
                wrap: false,
              },
              {
                content: "that",
                color: 0,
                offsetStartMs: 754360,
                offsetEndMs: 754680,
                wrap: true,
              },
              {
                content: "someone",
                color: 0,
                offsetStartMs: 754680,
                offsetEndMs: 755780,
                wrap: false,
              },
              {
                content: "may",
                color: 1,
                offsetStartMs: 755780,
                offsetEndMs: 757600,
                wrap: true,
              },
              {
                content: "use",
                color: 1,
                offsetStartMs: 757600,
                offsetEndMs: 757900,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 754180,
              offsetEndMs: 757900,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "it",
                color: 0,
                offsetStartMs: 757900,
                offsetEndMs: 758060,
                wrap: false,
              },
              {
                content: "in",
                color: 0,
                offsetStartMs: 758060,
                offsetEndMs: 758180,
                wrap: false,
              },
              {
                content: "a",
                color: 0,
                offsetStartMs: 758180,
                offsetEndMs: 758280,
                wrap: false,
              },
              {
                content: "way",
                color: 0,
                offsetStartMs: 758280,
                offsetEndMs: 758380,
                wrap: false,
              },
              {
                content: "that",
                color: 0,
                offsetStartMs: 758380,
                offsetEndMs: 758560,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 757900,
              offsetEndMs: 758560,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "is",
                color: 0,
                offsetStartMs: 758560,
                offsetEndMs: 758760,
                wrap: false,
              },
              {
                content: "bad",
                color: 0,
                offsetStartMs: 758760,
                offsetEndMs: 759100,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 758560,
              offsetEndMs: 759100,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "Even",
                color: 0,
                offsetStartMs: 760260,
                offsetEndMs: 760860,
                wrap: false,
              },
              {
                content: "if",
                color: 0,
                offsetStartMs: 760860,
                offsetEndMs: 761080,
                wrap: false,
              },
              {
                content: "they",
                color: 0,
                offsetStartMs: 761080,
                offsetEndMs: 761280,
                wrap: true,
              },
              {
                content: "weren't",
                color: 0,
                offsetStartMs: 761280,
                offsetEndMs: 761480,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 760260,
              offsetEndMs: 761480,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "going",
                color: 0,
                offsetStartMs: 761480,
                offsetEndMs: 761640,
                wrap: false,
              },
              {
                content: "to",
                color: 0,
                offsetStartMs: 761640,
                offsetEndMs: 761720,
                wrap: false,
              },
              {
                content: "use",
                color: 1,
                offsetStartMs: 761720,
                offsetEndMs: 761840,
                wrap: false,
              },
              {
                content: "it",
                color: 1,
                offsetStartMs: 761840,
                offsetEndMs: 761960,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 761480,
              offsetEndMs: 761960,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "in",
                color: 0,
                offsetStartMs: 761960,
                offsetEndMs: 762000,
                wrap: false,
              },
              {
                content: "a",
                color: 0,
                offsetStartMs: 762000,
                offsetEndMs: 762080,
                wrap: false,
              },
              {
                content: "way",
                color: 0,
                offsetStartMs: 762080,
                offsetEndMs: 762180,
                wrap: false,
              },
              {
                content: "that's",
                color: 0,
                offsetStartMs: 762180,
                offsetEndMs: 762360,
                wrap: true,
              },
              {
                content: "bad",
                color: 0,
                offsetStartMs: 762360,
                offsetEndMs: 762520,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 761960,
              offsetEndMs: 762520,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "that",
                color: 0,
                offsetStartMs: 762520,
                offsetEndMs: 762640,
                wrap: false,
              },
              {
                content: "somebody",
                color: 0,
                offsetStartMs: 762640,
                offsetEndMs: 762920,
                wrap: true,
              },
              {
                content: "could",
                color: 0,
                offsetStartMs: 762920,
                offsetEndMs: 763200,
                wrap: false,
              },
              {
                content: "take",
                color: 1,
                offsetStartMs: 763200,
                offsetEndMs: 763440,
                wrap: false,
              },
              {
                content: "it",
                color: 1,
                offsetStartMs: 763440,
                offsetEndMs: 763620,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 762520,
              offsetEndMs: 763620,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "from",
                color: 0,
                offsetStartMs: 763620,
                offsetEndMs: 763820,
                wrap: false,
              },
              {
                content: "them",
                color: 0,
                offsetStartMs: 763820,
                offsetEndMs: 764040,
                wrap: false,
              },
              {
                content: "and",
                color: 0,
                offsetStartMs: 764040,
                offsetEndMs: 764200,
                wrap: true,
              },
              {
                content: "use",
                color: 0,
                offsetStartMs: 764200,
                offsetEndMs: 764340,
                wrap: false,
              },
              {
                content: "it",
                color: 0,
                offsetStartMs: 764340,
                offsetEndMs: 764480,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 763620,
              offsetEndMs: 764480,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "in",
                color: 0,
                offsetStartMs: 764480,
                offsetEndMs: 764580,
                wrap: false,
              },
              {
                content: "a",
                color: 2,
                offsetStartMs: 764580,
                offsetEndMs: 764640,
                wrap: false,
              },
              {
                content: "way",
                color: 2,
                offsetStartMs: 764640,
                offsetEndMs: 764760,
                wrap: false,
              },
              {
                content: "",
                color: 0,
                offsetStartMs: 764480,
                offsetEndMs: 764580,
                wrap: false,
              },
              {
                content: "that's",
                color: 1,
                offsetStartMs: 764760,
                offsetEndMs: 764980,
                wrap: true,
              },
              {
                content: "bad",
                color: 0,
                offsetStartMs: 764980,
                offsetEndMs: 765240,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 764480,
              offsetEndMs: 765240,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "That",
                color: 0,
                offsetStartMs: 766120,
                offsetEndMs: 766420,
                wrap: false,
              },
              {
                content: "I",
                color: 0,
                offsetStartMs: 766420,
                offsetEndMs: 766660,
                wrap: false,
              },
              {
                content: "think",
                color: 0,
                offsetStartMs: 766660,
                offsetEndMs: 766800,
                wrap: false,
              },
              {
                content: "is",
                color: 0,
                offsetStartMs: 766800,
                offsetEndMs: 766920,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 766120,
              offsetEndMs: 766920,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
          {
            elements: [
              {
                content: "quite",
                color: 0,
                offsetStartMs: 766920,
                offsetEndMs: 767360,
                wrap: false,
              },
              {
                content: "a",
                color: 0,
                offsetStartMs: 767360,
                offsetEndMs: 767460,
                wrap: false,
              },
              {
                content: "big",
                color: 2,
                offsetStartMs: 767460,
                offsetEndMs: 767560,
                wrap: true,
              },
              {
                content: "danger",
                color: 2,
                offsetStartMs: 767560,
                offsetEndMs: 767840,
                wrap: false,
              },
            ],
            source: {
              offsetStartMs: 766920,
              offsetEndMs: 767840,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
        ],
        source: {
          offsetStartMs: 730000,
          offsetEndMs: 768120,
        },
      },
    ],
    emojiPlans: [
      {
        sceneId: "S.000",
        frames: [
          {
            elements: [
              {
                content: "🫵",
                offsetStartMs: 730000,
                offsetEndMs: 730220,
              },
            ],
            source: {
              offsetStartMs: 730000,
              offsetEndMs: 730220,
            },
          },
          {
            elements: [
              {
                content: "😈",
                offsetStartMs: 730420,
                offsetEndMs: 731300,
              },
            ],
            source: {
              offsetStartMs: 730420,
              offsetEndMs: 731300,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
              coveredLayers: [
                {
                  name: "VHOOK",
                  coveredLayerSource: {
                    offsetStartMs: 730000,
                    offsetEndMs: 733000,
                  },
                },
              ],
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 731300,
              offsetEndMs: 732660,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
              coveredLayers: [
                {
                  name: "VHOOK",
                  coveredLayerSource: {
                    offsetStartMs: 730000,
                    offsetEndMs: 733000,
                  },
                },
              ],
            },
          },
          {
            elements: [
              {
                content: "🧠",
                offsetStartMs: 732660,
                offsetEndMs: 734720,
              },
            ],
            source: {
              offsetStartMs: 732660,
              offsetEndMs: 734720,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
              coveredLayers: [
                {
                  name: "VHOOK",
                  coveredLayerSource: {
                    offsetStartMs: 730000,
                    offsetEndMs: 733000,
                  },
                },
              ],
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 734720,
              offsetEndMs: 735260,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [
              {
                content: "👑",
                offsetStartMs: 735260,
                offsetEndMs: 736100,
              },
            ],
            source: {
              offsetStartMs: 735260,
              offsetEndMs: 736100,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 736620,
              offsetEndMs: 737100,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 737100,
              offsetEndMs: 738340,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 738600,
              offsetEndMs: 739240,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 739240,
              offsetEndMs: 743060,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 744520,
              offsetEndMs: 745940,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [
              {
                content: "👑",
                offsetStartMs: 745940,
                offsetEndMs: 747300,
              },
            ],
            source: {
              offsetStartMs: 745940,
              offsetEndMs: 747300,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 747520,
              offsetEndMs: 748420,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 748420,
              offsetEndMs: 748820,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 748820,
              offsetEndMs: 749260,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 749260,
              offsetEndMs: 749980,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 749980,
              offsetEndMs: 750720,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 750720,
              offsetEndMs: 751380,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 751380,
              offsetEndMs: 751800,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 752000,
              offsetEndMs: 752720,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 752720,
              offsetEndMs: 754180,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 754180,
              offsetEndMs: 757900,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 757900,
              offsetEndMs: 758560,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 758560,
              offsetEndMs: 759100,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 760260,
              offsetEndMs: 761480,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 761480,
              offsetEndMs: 761960,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 761960,
              offsetEndMs: 762520,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 762520,
              offsetEndMs: 763620,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 763620,
              offsetEndMs: 764480,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 764480,
              offsetEndMs: 765240,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [],
            source: {
              offsetStartMs: 766120,
              offsetEndMs: 766920,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
          {
            elements: [
              {
                content: "⚠️",
                offsetStartMs: 766920,
                offsetEndMs: 767840,
              },
            ],
            source: {
              offsetStartMs: 766920,
              offsetEndMs: 767840,
            },
            position: {
              hAlign: "center",
              bPct: 6.72,
              lPct: 50,
            },
          },
        ],
        source: {
          offsetStartMs: 730000,
          offsetEndMs: 768120,
        },
      },
    ],
    vHookPlans: [
      {
        frames: [
          {
            elements: [
              {
                content: "Elon",
                wrap: false,
              },
              {
                content: "Musk's",
                wrap: true,
              },
              {
                content: "warning",
                wrap: false,
              },
              {
                content: "on",
                wrap: false,
              },
              {
                content: "the",
                wrap: true,
              },
              {
                content: "dangers",
                wrap: false,
              },
              {
                content: "of",
                wrap: false,
              },
              {
                content: "AI",
                wrap: false,
              },
            ],
            bgcolor: "&H00000000",
            color: "&H00ffffff",
            source: {
              offsetStartMs: 730000,
              offsetEndMs: 733000,
            },
            position: {
              hAlign: "center",
              bPct: 19.14,
              lPct: 16.67,
              rPct: 16.67,
            },
          },
        ],
        source: {
          offsetStartMs: 730000,
          offsetEndMs: 733000,
          absoluteBase: 0,
        },
      },
    ],
    version: "NEW",
  },
  reLayoutPlans: [
    {
      sceneId: "S.000",
      cropKeyFrames: [
        {
          keyFrameRects: [
            {
              cropRect: {
                w: 608,
                h: 1080,
                l: 882,
                t: 0,
              },
              headRects: [
                {
                  w: 335,
                  h: 477,
                  l: 1018.5,
                  t: 156.5,
                },
              ],
            },
          ],
          layoutType: "fill",
          offsetMs: 730005.29,
          frameIndex: 3118,
          cameraPosIndex: 0,
          cameraPosDuration: 13471.829999999958,
        },
        {
          keyFrameRects: [
            {
              cropRect: {
                w: 608,
                h: 1080,
                l: 101,
                t: 0,
              },
              headRects: [
                {
                  w: 108,
                  h: 154,
                  l: 351,
                  t: 140,
                },
                {
                  w: 120,
                  h: 169,
                  l: 1442,
                  t: 93.5,
                },
              ],
            },
          ],
          layoutType: "fill",
          offsetMs: 743477.12,
          frameIndex: 3441,
          cameraPosIndex: 1,
          cameraPosDuration: 24649.709999999963,
        },
      ],
    },
  ],
  pendingNew: false,
  renderPreferenceOverride: {
    useMultipleLayout: true,
    enableFillLayout: true,
    enableFitLayout: false,
    enableSplitLayout: false,
    enableThreeLayout: false,
    enableFourLayout: false,
    fitLayoutCropRatio: "4:3",
    enableVisualHook: true,
    enableWatermark: false,
    enableCrop: true,
    enableCaption: true,
    enableCaptionAnimation: false,
    captionStyle: null,
    captionPosition: "auto",
    enableHighlight: true,
    enableEmoji: true,
    emojiStyle: null,
    enableUppercase: true,
    highlightColor: {
      primary: "#04f827",
      secondary: "#FFFD03",
    },
    font: {
      size: "Large",
      numericalSize: 56,
      color: "#ffffff",
      stroke: {
        enabled: true,
        color: "#000000",
        width: 10,
      },
      style: ["900"],
      textDecoration: "",
      family: "Montserrat",
      shadow: {
        enabled: true,
        color: "#000000",
        x: 2,
        y: 2,
        blur: 5,
      },
    },
    screenOverlay: null,
    screenOverlays: [],
    screenOverlayFileId: null,
    rerenderUseNewFaceDetectModel: true,
  },
  renderTrace: {
    runId: "20230511032800826.RC",
    workerGit: "e73ee1ad",
    workerUrl: "http://10.128.0.5:8000/api/FullProjectRun",
  },
  version: "20230508",
};

export const EMOJI_URL_MAP: Record<string, string> = {
  "🫵": "https://storage.googleapis.com/opus-clip-pub/overlay/apple-emoji-144x144/index-pointing-at-the-viewer.png",
  "😈": "https://storage.googleapis.com/opus-clip-pub/overlay/apple-emoji-144x144/smiling-face-with-horns.png",
  "🧠": "https://storage.googleapis.com/opus-clip-pub/overlay/apple-emoji-144x144/brain.png",
  "👑": "https://storage.googleapis.com/opus-clip-pub/overlay/apple-emoji-144x144/crown.png",
  "⚠️": "https://storage.googleapis.com/opus-clip-pub/overlay/apple-emoji-144x144/warning.png",
};
